#Numpy

In [ ]:
# Numerical Python
# Advantages:
# 1. allow several mathematical Operations
# 2. Faster application
from time import process_time
a=[i for i in range(1000000)]
start_time=process_time()
a=[i+5 for i in a]
end_time=process_time()
print(end_time-start_time)



0.078125
0.0


In [17]:
import numpy as np
np_array=np.array([i for i in range(1000000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0


In [19]:
print(type(np_array))

<class 'numpy.ndarray'>


In [21]:
np_array.shape

(1000000,)

In [27]:
#Create anumpy aarray with zeros
x=np.zeros((5,5))#to crate this you usr Np.zeros((fill shpe you have to give ))
print(x)
#TO Create array of ones
x=np.ones((2,3))
print(x)
x=np.full((3,3),7)
print(x)
x=np.empty((3,3))
x.fill(32)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[32. 32. 32.]
 [32. 32. 32.]
 [32. 32. 32.]]


In [ ]:
#Fill with random value
import random
a=np.random.randint(0,100,(3,3))
print(a)


[[97 10 67]
 [88 96 68]
 [77 31 73]]


In [32]:
#Transpose
a=np.transpose(a)
print(a)

[[97 88 77]
 [10 96 31]
 [67 68 73]]


In [ ]:
b=a.reshape(3,3)
print(b)

[[97 88 77]
 [10 96 31]
 [67 68 73]]


In [1]:

import numpy as np 
a=np.array([10,32,43])
print(a)

[10 32 43]


Basic arihmetic operation in numpy

In [2]:
a=np.array([2,3,43,4])
b=np.array([3,34,23,2])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)


[ 5 37 66  6]
[ -1 -31  20   2]
[  6 102 989   8]
[0.66666667 0.08823529 1.86956522 2.        ]
[                  8   16677181699666569 5694331190162838499
                  16]


Aggregation function

In [3]:
a=np.array([2,3,4,1,2,3,43])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))#Max
print(np.std(a))#Standard Deviation
print(np.var(a))#Variance


58
8.285714285714286
3.0
1
43
14.199741302616204
201.63265306122452


In [ ]:
a=np.array([[2,3],[3,5]])
b=np.array([[2,4],[4,23]])
print(np.dot(a,b))
print(np.linalg.inv(a))
print(np.linalg.det(a))
print(np.linalg.eig(a))


[[ 16  77]
 [ 26 127]]
[[ 5. -3.]
 [-3.  2.]]
0.9999999999999991
0.9999999999999991
EigResult(eigenvalues=array([0.14589803, 6.85410197]), eigenvectors=array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]]))


Trignometric Values

In [9]:
a=np.array([0,1,2])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[0.         0.84147098 0.90929743]
[ 1.          0.54030231 -0.41614684]
[ 0.          1.55740772 -2.18503986]


In [10]:
a=np.array([2,3.2,3.34])
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[2. 3. 3.]
[2. 3. 3.]
[2. 4. 4.]


In [12]:
#stastical Function
a=np.array([2,3,43,23])
print(np.percentile(a,50))
print(np.corrcoef(a))


13.0
1.0
